package settingdust.calypsos_nightvision_goggles.item.nightvision_goggles.variant

import settingdust.calypsos_nightvision_goggles.item.nightvision_goggles.NightvisionGogglesVariant

object RegularVariant : NightvisionGogglesVariant